rootProject.name = "TursomServer"
include("ts-core")
include("ts-core:ts-encrypt")
include("ts-core:ts-buffer")
include("ts-core:ts-datastruct")
include("ts-core:ts-pool")
include("ts-core:ts-hash")
include("ts-core:ts-log")
include("ts-core:ts-delegation")
include("ts-socket")
//include("web", "aop", "database", "utils", "utils:xml", "utils:async-http", "web:netty-web")
//include("socket", "socket:socket-async")
//include("AsyncSocket")
//include("log")
//include("json")
//include("utils:yaml")
//include("web:web-coroutine")
//include("microservices")
//include("database:database-mysql")
//include("database:mongodb")
//include("database:mongodb:mongodb-async")
//include("database:redis")
//include("utils:ws-client")
//include("utils:mail")
//include("utils:csv")
//include("utils:delegation")
//include("utils:observer")
//include("utils:TrafficForward")
//include("utils:performance-test")
//include("utils:math")
//include("utils:json")